---

- name: Install repository Postgresql10
  yum: name=https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm state=present


- name: ensure a list of postgres packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql10-server
    - postgresql10-contrib
    - postgresql10
    - postgresql10-odbc

- name: enable postgres service
  systemd:
    name: postgresql-10
    enabled: yes


- name: Initiate database
  #shell: "/usr/pgsql-10/bin/initdb -D /var/lib/pgsql/10/data"  
  shell: "{{postgresql_bin_path}}/initdb -D {{postgresql_data_dir}}"  
  become: yes
  become_user: postgres


- name: Make sure postgres service is running
  systemd:
    state: started
    name: postgresql-10


- name: adding firewall rules for postgres service
  command: firewall-cmd --add-service=postgresql --permanent
  notify: Reloading firewalld rules


- name: Configure host based authentication.
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/10/data/pg_hba.conf
    owner: "{{postgresql_user}}"
    group: "{{postgresql_group}}"
    mode: 0600



- name: Copy modified postgresql.conf to allow connection from external.
  copy:
    src: postgresql.conf
    dest: /var/lib/pgsql/10/data/postgresql.conf
    owner: "{{postgresql_user}}"
    group: "{{postgresql_group}}"
    mode: 0600


- name: Restart postgres service
  systemd:
    state: restarted
    name: postgresql-10
